"""empty message

Revision ID: 05feb9df7d42
Revises: 
Create Date: 2020-11-29 21:19:44.992882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05feb9df7d42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food', 'food_desc')
    op.drop_column('food_detail', 'food_group')
    op.drop_column('food_detail', 'processed_desc')
    op.drop_column('food_detail', 'ingredient_list')
    op.drop_constraint('food_unit_food_id_fkey', 'food_unit', type_='foreignkey')
    op.create_foreign_key(None, 'food_unit', 'account', ['food_id'], ['id'])
    op.add_column('user_session', sa.Column('account_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'user_session', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.drop_column('user_session', 'account_id')
    op.drop_constraint(None, 'food_unit', type_='foreignkey')
    op.create_foreign_key('food_unit_food_id_fkey', 'food_unit', 'nut_per_100_gram', ['food_id'], ['food_id'])
    op.add_column('food_detail', sa.Column('ingredient_list', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('food_detail', sa.Column('processed_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('food_detail', sa.Column('food_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('food', sa.Column('food_desc', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
